<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>UnspottableExpanded</AssemblyName>
    <RootNamespace>UnspottableExpanded</RootNamespace>
    <Version>0.9.8</Version>
    <Deterministic>true</Deterministic>
    <DebugType>portable</DebugType>
    <GameDir Condition="'$(UE_GAME_DIR)' != ''">$(UE_GAME_DIR)</GameDir>
    <ManagedDir Condition="'$(GameDir)' != ''">$(GameDir)\Unspottable_Data\Managed</ManagedDir>
    <BepInExCoreDir Condition="'$(GameDir)' != ''">$(GameDir)\BepInEx\core</BepInExCoreDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx.Core"><HintPath>$(BepInExCoreDir)\BepInEx.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="BepInEx.Unity.Mono"><HintPath>$(BepInExCoreDir)\BepInEx.Unity.Mono.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(ManagedDir)\UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(ManagedDir)\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.PhysicsModule"><HintPath>$(ManagedDir)\UnityEngine.PhysicsModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Rewired_Core"><HintPath>$(ManagedDir)\Rewired_Core.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
